# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'
strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_10_x:
      node_version: 10.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(node_version)'
  displayName: 'Install Node.js $(node_version)'

- script: |
    npm install
    npm test -- --reporter mocha-junit-reporter
  displayName: 'npm install and test'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: ./test-results.xml
